Repository adinhodovic/tailscale-exporter, pull requests merged in 2025-10, with the labels that each got.

#20 chore: Add tailscale client side grafana dashboard image
  docs/images/grafana-machine-1.png
Labels: chore

#21 ci: Build and upload binaries on release
  .github/workflows/ci.yml
  .gitignore
  Makefile
Labels: ci

#22 ci: Change git action for releases
  .github/workflows/ci.yml
Labels: ci

#23 ci: Ensure we checkout code
  .github/workflows/ci.yml
Labels: ci

#24 ci: Ensure proper permissions to write content
  .github/workflows/ci.yml
Labels: ci

#25 docs: Add docs for binary installation
  README.md
Labels: docs

#27 fix(collector): Tailscale devices routes advertised not behaving correctly
  cmd/tailscale-exporter/root.go
  collector/collector.go
  collector/collector_test.go
  collector/devices.go
  collector/devices_test.go
Labels: fix

#28 feat(helm): Bump default image tag
  deploy/charts/tailscale-exporter/Chart.yaml
  deploy/charts/tailscale-exporter/README.md
Labels: feat

#30 fix: Move unapproved alerts to use tailnet metrics
  tailscale-mixin/alerts/alerts.libsonnet
  tailscale-mixin/config.libsonnet
  tailscale-mixin/prometheus_alerts.yaml
  tailscale-mixin/tests/tests.yaml
Labels: fix
